version: '2'
services:
  web:
    build: .
  mysql:
    image: datajoint/mysql:5.7
    volumes:
      - ./my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    command: --character-set-server=utf8
